services:
  labybot:
    image: labybot:0.0.6
    container_name: labybot
    pull_policy: never # Force using local image
    volumes:
      - ./config_Yumi.json:/bot/config.json
      - ./resources:/bot/resources
      - labybot_data:/bot/save
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  labybot_data:
    name: labybot_data
