services:
  labybot:
    image: labybot:2.0.0
    container_name: labybot
    pull_policy: never # Force using local image
    volumes:
      - ./config:/bot/config
      - ./resources:/bot/resources
      - labybot_data:/bot/save
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  labybot_data:
    name: labybot_data
